export default {    
    url: 'http://api.bhatiahospital.org/api/v1/',    
    env: 'local',
    Route: {
      login: 'account/check-login',
      signup: 'account/signup',
      otp: 'account/check-otp',
      resendOtp: 'account/resend-otp',
      logout: 'account/logout',
      profile: 'profile',
      updateProfile: 'profile/update',
      allPatient: 'patient',
      addPatient: 'patient/add',
      editPatient: "patient/edit",
      viewPatient: "patient/view",
      removePatient: "patient/remove",
      speciality: "speciality",
      viewSpeciality: "speciality/view",
      doctors: "doctor",
      doctorView: "doctor/view",
      bookedAppointment: "appointment-request",
      bookAppointment: "appointment-request/add",
      viewBookedAppointment: "appointment-request/view",
      requestAddmission: "admission-request",
      addRequestAddmission: "admission-request/add",
      ViewRequestAddmission: "admission-request/view",
      roomList: "room",
      viewRoom: "room/view",
      medicalTest: "medical-test",
      viewMedicalTest: "medical-test/view",
      requestMedicalTest: "medical-test-request",
      addRequestMedicalTest: "medical-test-request/add",
      viewRequestMedicalTest: "medical-test-request/view",
      requestInPatient: "in-patient",
      requestFeedback: "feedback/question",
      submitFeedback: "feedback/add",
      feedbackGiven: "feedback/allow-feedback",
      confirmPayment: "payment/confirm",
      deletePayment: "payment/delete",
      paidBill: "pending-bill-request",
      pendingBill: "pending-bill-request/search",
      payBill: "pending-bill-request/add",
    },
    payment: {name:'payment', key:'rzp_live_wGz9LdOgBtrpZC', description: '', color: '#23B8BF'}
  };
